Feat/app/new error handling
jeffersonlizar/bgc-integration pull request #5
Opened 2020-11-26 23:01 UTC by tomasdiaztoro

Add new exceptions handling, including error codes.
Status is no included in error responses.

Related backed PR: https://github.com/cornershop/cornershop-backend/pull/17034

2020-11-27 15:57 UTC, richardbm commented on integration/app.py
> +            logger.info("BGC adapter unprocessable entity exception", extra=get_logger_data(check_data, e.error_message))
We just need to catch `GenericAPIException`. all exceptions raised that extend that one will be caught. The logs could get the message from the exception.  maybe `logger.info("BGC request error {e.error_message}"`

we could also have a decorator for the view that caught `GenericAPIException` and log and return the error message. What do you think @tomasdiaztoro @jeffersonlizar ?

2020-11-27 18:59 UTC, tomasdiaztoro commented on integration/app.py
> +            logger.info("BGC adapter unprocessable entity exception", extra=get_logger_data(check_data, e.error_message))
agree with the first, the decorator seems a bit unneeded

2020-11-27 19:38 UTC, tomasdiaztoro commented on integration/app.py
> +            logger.info("BGC adapter unprocessable entity exception", extra=get_logger_data(check_data, e.error_message))
but we said that the Generic exception must reach sentry 👁️

2020-11-30 22:08 UTC, richardbm commented on integration/app.py
> +            logger.info("BGC adapter unprocessable entity exception", extra=get_logger_data(check_data, e.error_message))
We need to raise an exception for not handled responses. we were using `GenericAPIException`. but we could also define another one that does not extend from GenericAPIException.

2020-11-30 22:09 UTC, richardbm commented on integration/app.py
> +            logger.info("BGC adapter unprocessable entity exception", extra=get_logger_data(check_data, e.error_message))
the use of the decorator for the exception handling is optional. I don't have a strong opinion thee

2020-12-01 17:09 UTC, richardbm requested changes

2020-12-01 17:09 UTC, richardbm commented on integration/app.py
> +        if not validate_request(request.headers.get("Authorization")):
this service `validate_request` should raise the exception and you should catch it here and send to get_error_response the caught exception. maybe the exceptions for the satellite should have the status code to be returned. so you don't need to pass it, and you could be able to raise different exceptions that returns  different status codes

2020-12-08 02:41 UTC, jeffersonlizar approved these changes
LGTM

2020-12-09 15:54 UTC, richardbm approved these changes

2020-12-09 18:19 UTC, merged